services:
  app:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: symfony_app
    working_dir: /var/www
    volumes:
      - ./:/var/www
    depends_on:
      - database
    environment:
      - APP_ENV=dev
      - APP_SECRET=ea1df7bffeb64c8e5e41f5b81ee10ac9
      - DATABASE_URL=${DATABASE_URL:-postgresql://app:!ChangeMe!@database:5432/app?serverVersion=16&charset=utf8}

  nginx:
    image: nginx:alpine
    container_name: symfony_nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  database:
    image: postgres:16-alpine
    container_name: symfony_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: '!ChangeMe!'
    volumes:
      - database_data:/var/lib/postgresql/data:rw

  pgadmin:
    image: dpage/pgadmin4
    container_name: symfony_pgadmin
    ports:
      - "8081:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - database

volumes:
  database_data: